//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameUtilityApp.Essential.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLib() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameUtilityApp.Essential.Language.StringLib", typeof(StringLib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   App Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Setting {
            get {
                return ResourceManager.GetString("App Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while saving.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_1 {
            get {
                return ResourceManager.GetString("ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no font. Do you want to install it? 
        ///If not installed, the program will be terminated.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_2 {
            get {
                return ResourceManager.GetString("ERROR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while saving the registry.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_3 {
            get {
                return ResourceManager.GetString("ERROR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For Windows 10, only up to 31 are supported in the control panel.
        ///You can still set it up, but we cannot guarantee its application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string keyboardspeed_notic {
            get {
                return ResourceManager.GetString("keyboardspeed notic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soon, font installation begins. Complete the font installation in a new window and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_1 {
            get {
                return ResourceManager.GetString("Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the user?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_10 {
            get {
                return ResourceManager.GetString("Message_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The user has been deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_11 {
            get {
                return ResourceManager.GetString("Message_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the group?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_12 {
            get {
                return ResourceManager.GetString("Message_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The group has been deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_13 {
            get {
                return ResourceManager.GetString("Message_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applied.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_2 {
            get {
                return ResourceManager.GetString("Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no nickname.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_3 {
            get {
                return ResourceManager.GetString("Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your nickname has been confirmed. Click the Save button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_4 {
            get {
                return ResourceManager.GetString("Message_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_5 {
            get {
                return ResourceManager.GetString("Message_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_6 {
            get {
                return ResourceManager.GetString("Message_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_7 {
            get {
                return ResourceManager.GetString("Message_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save a new nick과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_8 {
            get {
                return ResourceManager.GetString("Message_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last sync: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message_9 {
            get {
                return ResourceManager.GetString("Message_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not seeing again과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string notSeeAgain {
            get {
                return ResourceManager.GetString("notSeeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ok과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Text_1 {
            get {
                return ResourceManager.GetString("Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Team Match Score Calculator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_1 {
            get {
                return ResourceManager.GetString("Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nickname Tracker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_2 {
            get {
                return ResourceManager.GetString("Title_2", resourceCulture);
            }
        }
    }
}
